MiaoShaProject/Controllers/GoodController.cs
using Beyondbit.Framework;
using BO;
using Common;
using Common.Cache;
using Entity;
using MiaoShaProject.Filter;
using Newtonsoft.Json;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace MiaoShaProject.Controllers
{
    //[LoginCheckFilter(IsCheck = true)]
    public class GoodController : Controller
    {

        private readonly Lazy<GoodBO> _lazyGoodBO;
        private readonly Lazy<MiaoShaOrderBO> _lazyMiaoShaOrderBO;
        private readonly Lazy<OrderInfoBO> _lazyOrderInfoBO;
        private readonly RedisCacheWriter cache = new RedisCacheWriter();

        public GoodController()
        {

            _lazyGoodBO = new Lazy<GoodBO>(ProxyService.Create<GoodBO>);
            _lazyMiaoShaOrderBO = new Lazy<MiaoShaOrderBO>(ProxyService.Create<MiaoShaOrderBO>);
            _lazyOrderInfoBO = new Lazy<OrderInfoBO>(ProxyService.Create<OrderInfoBO>);
        }

        public GoodBO GoodBO
        {
            get { return _lazyGoodBO.Value; }
        }

        public MiaoShaOrderBO MiaoShaOrderBO
        {
            get { return _lazyMiaoShaOrderBO.Value; }
        }
        public OrderInfoBO OrderInfoBO
        {
            get { return _lazyOrderInfoBO.Value; }
        }

        // GET: Good
        public ActionResult Index()
        {
            var model = GoodBO.GetGood();
            return View(model);
        }

        /// <summary>
        /// 商品详情页
        /// </summary>
        /// <param name="id"></param>
        /// <returns></returns>
        public ActionResult GoodDetail(Int64? id)
        {
            String token = this.HttpContext.Request.Cookies["token"].Value;
            var user = JsonConvert.DeserializeObject<MiaoShaUser>(CacheHelper.GetCache(token).ToString());
            var good = GoodBO.GetGoodById(Convert.ToInt64(id));
            GoodDetailView model = new GoodDetailView();
            double remainSeconds;
            int miaoshaStatus = 0;
            if (DateTime.Now < good.StartDate)
            {//秒杀还没开始，倒计时
                miaoshaStatus = 0;
                remainSeconds = (good.StartDate.Value - good.EndDate.Value).TotalMilliseconds;
            }
            else if (DateTime.Now > good.EndDate)
            {//秒杀已经结束
                miaoshaStatus = 2;
                remainSeconds = -1;
            }
            else
            {//秒杀进行中
                miaoshaStatus = 1;
                remainSeconds = 0;
            }
            model.Good = good;
            model.MiaoShaStatus = miaoshaStatus;
            model.RemainSeconds = remainSeconds;
            model.User = user;
            return View(model);
        }


        /// <summary>
        /// 秒杀功能
        /// </summary>
        /// <param name="id"></param>
        /// <returns></returns>
        public ActionResult MiaoSha(Int64 goodsId)
        {
            String token = this.HttpContext.Request.Cookies["token"].Value;
            var user = JsonConvert.DeserializeObject<MiaoShaUser>(CacheHelper.GetCache(token).ToString());
            if (user == null)
            {
                return RedirectToAction("Index", "Home");
            }
            #region 优化前代码
            ////判断库存
            //Good good = GoodBO.GetGoodById(goodsId);
            //int stock = good.StockCount;
            //if (stock <= 0)
            //{
            //    return Json(ResponseResult.Error(CodeMessage.MiaoShaOverError));
            //}
            ////判断是否已经秒杀到了
            //MiaoShaOrder order = MiaoShaOrderBO.GetMiaoshaOrderByUserIdGoodsId(user.Id, goodsId);
            //if (order != null)
            //{
            //    return Json(ResponseResult.Error(CodeMessage.MiaoShaRepeat));
            //}
            ////减库存 下订单 写入秒杀订单
            //var orderInfo = OrderInfoBO.MiaoSha(user, good);
            //if (orderInfo != null)
            //{
            //    return Json(ResponseResult.Succeed(orderInfo));
            //}
            //else
            //{
            //    return Json(ResponseResult.Error(CodeMessage.MiaoShaOverError));
            //}

            #endregion

            #region 优化后代码
            //内存标记，减少redis访问
            //预减库存
            var stock = Convert.ToInt64(cache.GetCache("GoodId" + goodsId));
            if (stock < 0)
            {
                return Json(ResponseResult.Error(CodeMessage.MiaoShaOverError));
            }

            //判断是否已经秒杀到了
            MiaoShaOrder order = MiaoShaOrderBO.GetMiaoshaOrderByUserIdGoodsId(user.Id, goodsId);
            if (order != null)
            {
                return Json(ResponseResult.Error(CodeMessage.MiaoShaRepeat));
            }
            //入队
            MiaoShaMessage mm = new MiaoShaMessage();
            mm.MiaoShaUser = user;
            mm.GoodId = goodsId;
            MQSender ms = new MQSender();
            MQReceiver mr = new MQReceiver();
            ms.sendMiaoshaMessage(mm);
            mr.Consumer();
            return Json(ResponseResult.Succeed("成功"));
            #endregion

        }
    }
}

MiaoShaProject/Controllers/HomeController.cs
using Beyondbit.Framework;
using BO;
using Common;
using Common.Cache;
using Entity;
using Newtonsoft.Json;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace MiaoShaProject.Controllers
{
    public class HomeController : Controller
    {

        private  readonly Lazy<MiaoShaUserBO> _lazyMiaoShaUserBO ;

        public HomeController()
        {
            _lazyMiaoShaUserBO = new Lazy<MiaoShaUserBO>(ProxyService.Create<MiaoShaUserBO>);
        }

        public MiaoShaUserBO MiaoShaUserBO
        {
            get { return _lazyMiaoShaUserBO.Value; }
        }

        public ActionResult Index()
        {
            return View();
        }

        public ActionResult About()
        {
            ViewBag.Message = "Your application description page.";

            return View();
        }

        public ActionResult Contact()
        {
            ViewBag.Message = "Your contact page.";

            return View();
        }

        [HttpPost]
        public ActionResult Login(MiaoShaUser user)
        {
           var miaoshaUser= MiaoShaUserBO.Login(user);
            ResponseResult responseResult;
            if (miaoshaUser != null)
            {
                
                // Session["User"] = model;用redis分布式缓存模拟session
                String token = Guid.NewGuid().ToString();

                CacheHelper.AddCache(token, JsonConvert.SerializeObject(miaoshaUser), DateTime.Now.AddMinutes(20));

                //往客户端写入cookie
                Response.Cookies["token"].Value = token;

                responseResult = ResponseResult.Succeed(miaoshaUser);
            }
            else
            {
                responseResult=ResponseResult.Error(CodeMessage.LoginError);
            }
            return Json(responseResult);

        }


    }
}

MiaoShaProject/Views/Good/GoodDetail.cshtml
@model Entity.GoodDetailView

@{
    ViewBag.Title = "商品详情页";
}
<div class="panel panel-default">
    <div class="panel-heading">秒杀商品详情</div>
    <div class="panel-body">
        @if (Model.User == null)
        {
            <span> 您还没有登录，请登陆后再操作<br /></span>
            <span>没有收货地址的提示。。。</span>
        }

    </div>
    <table class="table" id="goodslist">
        <tr>
            <td>商品名称</td>
            <td colspan="3">@Model.Good.Name</td>
        </tr>
        <tr>
            <td>商品图片</td>
            <td colspan="3"><img src="@Model.Good.Img" width="200" height="200" /></td>
        </tr>
        <tr>
            <td>秒杀开始时间</td>
            <td>@Model.Good.StartDate</td>
            <td id="miaoshaTip">
                <input type="hidden" id="remainSeconds" value="@Model.RemainSeconds" />
                @if (Model.MiaoShaStatus.Equals(0))
                {
                    <span>秒杀倒计时：<span id="countDown">@Model.RemainSeconds</span>秒</span>

                }               
                @if (Model.MiaoShaStatus.Equals(1))
                {
                    <span>秒杀进行中</span>}
                @if (Model.MiaoShaStatus.Equals(2))
                {<span>秒杀已结束</span>
                }
            </td>
            <td>
                <form id="miaoshaForm" method="post" action="@Url.Action("MiaoSha","Good")">
                    <button class="btn btn-primary btn-block" type="submit" id="buyButton">立即秒杀</button>
                    <input type="hidden" name="goodsId" value="@Model.Good.Id" />
                </form>
            </td>
        </tr>
        <tr>
            <td>商品原价</td>
            <td colspan="3">@Model.Good.Price</td>
        </tr>
        <tr>
            <td>秒杀价</td>
            <td colspan="3">@Model.Good.MiaoShaPrice</td>
        </tr>
        <tr>
            <td>库存数量</td>
            <td colspan="3">@Model.Good.StockCount</td>
        </tr>
    </table>
</div>
<script>
    $(function () {
        countDown();
    });

    function countDown() {
        var remainSeconds = $("#remainSeconds").val();
        var timeout;
        if (remainSeconds > 0) {//秒杀还没开始，倒计时
            $("#buyButton").attr("disabled", true);
            timeout = setTimeout(function () {
                $("#countDown").text(remainSeconds - 1);
                $("#remainSeconds").val(remainSeconds - 1);
                countDown();
            }, 1000);
        } else if (remainSeconds == 0) {//秒杀进行中
            $("#buyButton").attr("disabled", false);
            if (timeout) {
                clearTimeout(timeout);
            }
            $("#miaoshaTip").html("秒杀进行中");
        } else {//秒杀已经结束
            $("#buyButton").attr("disabled", true);
            $("#miaoshaTip").html("秒杀已经结束");
        }
    }

</script>

MiaoShaProject/Views/Good/Index.cshtml
@using Entity;
@model IEnumerable<Entity.Good>
@{
    ViewBag.Title = "商品列表";
}


<style type="text/css">
    html, body {
        height: 100%;
        width: 100%;
    }

    #goodslist td {
        border-top: 1px solid #39503f61;
    }

    body {
        background: url('../../Content/static/img/bg2.jpg') no-repeat;
        background-size: 100% 100%;
    }
</style>


<div class="panel panel-default" style="height:100%;background-color:rgba(222,222,222,0.8)">
    <div class="panel-heading">秒杀商品列表</div>
    <table class="table" id="goodslist">
        <tr>
            <td>商品名称</td>
            <td>商品图片</td>
            <td>商品原价</td>
            <td>秒杀价</td>
            <td>库存数量</td>
            <td>详情</td>
        </tr>
        @if (Model.Count() > 0)
        {
            var i = 0;

            foreach (var entity in Model)
            {
                <tr>
                    <td>@entity.Name</td>
                    <td>
                        <img src="@entity.Img" width="100" height="100" />

                    </td>
                    <td>@entity.Price</td>
                    <td>@entity.MiaoShaPrice</td>
                    <td>@entity.StockCount</td>
                    <td>@Html.ActionLink("商品详情", "GoodDetail", "Good", new { id = entity.Id } , new { @title = "查看详情" })</td>
                </tr>
            }
        }
        else
        {
            <tr>
                <td colspan="6" style="text-align: center; font-size: 12px;">
                    暂无数据
                </td>
            </tr>
        }
    </table>
</div>

MiaoShaProject/Views/Home/About.cshtml
@{
    ViewBag.Title = "About";
}
<h2>@ViewBag.Title.</h2>
<h3>@ViewBag.Message</h3>

<p>Use this area to provide additional information.</p>

MiaoShaProject/Views/Home/Contact.cshtml
@{
    ViewBag.Title = "Contact";
}
<h2>@ViewBag.Title.</h2>
<h3>@ViewBag.Message</h3>

<address>
    One Microsoft Way<br />
    Redmond, WA 98052-6399<br />
    <abbr title="Phone">P:</abbr>
    425.555.0100
</address>

<address>
    <strong>Support:</strong>   <a href="mailto:Support@example.com">Support@example.com</a><br />
    <strong>Marketing:</strong> <a href="mailto:Marketing@example.com">Marketing@example.com</a>
</address>

MiaoShaProject/Views/Home/Index.cshtml
@{
    ViewBag.Title = "Home Page";
}
<style type="text/css">
    html, body {
        height: 100%;
        width: 100%;
    }

    body {
        background: url('../../Content/static/img/bg.jpg') no-repeat;
        background-size: 100% 100%;
        padding-top: 100px;
    }
</style>
<form name="loginForm" id="loginForm" method="post" style="width:30%; margin:0 auto;">

    <h2 style="text-align:center; margin-bottom: 20px">用户登录</h2>

    <div class="form-group">
        <div class="row">
            <label class="form-label col-md-4">请输入手机号码</label>
            <div class="col-md-8">
                <input id="mobile" name="mobile" class="form-control" type="text" placeholder="手机号码" required="true" minlength="11" maxlength="11" value="18817802311" />
            </div>
            <div class="col-md-1">
            </div>
        </div>
    </div>

    <div class="form-group">
        <div class="row">
            <label class="form-label col-md-4">请输入密码</label>
            <div class="col-md-8">
                <input id="password" name="password" class="form-control" type="password" placeholder="密码" required="true" minlength="6" maxlength="16" value="123456"/>
            </div>
        </div>
    </div>

    <div class="row" style="margin-top:40px;">
        <div class="col-md-6">
            <button class="btn btn-primary btn-block" type="reset" onclick="reset()">重置</button>
        </div>
        <div class="col-md-6">
            <button class="btn btn-primary btn-block" type="submit" onclick="login()">登录</button>
        </div>
    </div>

</form>
<script>
    function login() {
        var password = md5($("#password").val());

        $.ajax({
            url: '@Url.Action("Login","Home")',
            type: "POST",
            data: {
                mobile: $("#mobile").val(),
                password: password
            },
            success: function (data) {
                if (data.Code == "1") {
                    layer.msg(data.Message);
                    window.location.href ='@Url.Action("Index","Good")';
                } else {
                    layer.msg(data.Message);
                }
            },
            error: function () {
                layer.closeAll();
            }
        });
    }
</script>

MiaoShaProject/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html>
<head>
    <meta http-equiv="Content-Type" content="text/html; charset=utf-8" />
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>@ViewBag.Title -我的秒杀项目</title>
    <link href="~/Content/static/layer/skin/default/layer.css" rel="stylesheet" />
    <link href="~/Content/static/bootstrap/css/bootstrap.css" rel="stylesheet" />
    <script src="~/Scripts/jquery-2.0.3.min.js"></script>
    <script src="~/Scripts/bootstrap.min.js"></script>
    <script src="~/Scripts/jquery.validate.js"></script>
    <script src="~/Scripts/respond.min.js"></script>
    <script src="~/Content/static/js/md5.min.js"></script>
    <script src="~/Content/static/layer/layer.js"></script>
</head>
<body>
    <div>
        @RenderBody()
        
        <footer>
            <p class="text-center">&copy; @DateTime.Now.Year - 我的 ASP.NET 应用程序</p>
        </footer>
    </div>

    @Scripts.Render("~/bundles/jquery")
    @Scripts.Render("~/bundles/bootstrap")
    @RenderSection("scripts", required: false)
</body>
</html>